// components/ui/Button/index.tsx
'use client';

import { useSoundEffect } from '@/hooks/useSoundEffect';
import { useSoundStore } from '@/stores/soundStore';
import { useThemeStore } from '@/stores/themeStore';
import type { ButtonParams } from '@/types/components';
import { useState } from 'react';

import { Flex } from 'antd';
import './index.scss';

/**
 * Button 组件用于渲染一个可交互的按钮。
 *
 * @param {string} props.text - 按钮上显示的文本内容
 * @param {'small' | 'medium' | 'large'} props.size - 按钮的尺寸大小
 * @param {React.ReactNode} props.icon - 按钮的图标
 * @param {() => void} props.onClick - 按钮点击事件处理函数
 **/
const Button = ({ text, size, icon, onClick, style }: ButtonParams) => {
  const [hasInteracted, setHasInteracted] = useState(false);
  const { theme } = useThemeStore();
  const { effectsVolume } = useSoundStore();

  const undertaleSound = useSoundEffect({ audioSrc: '/sounds/effects/undertale-button.wav' });
  // const touhouSound = useSoundEffect('/sounds/touhou-button.mp3')
  const handleMouseEnter = () => {
    if (hasInteracted) {
      if (effectsVolume) {
        if (theme === 'undertale') undertaleSound.play();
        // else
        //   touhouSound.play()
      }
    }
  };

  const handleClick = () => {
    // 标记用户已交互
    if (!hasInteracted) {
      setHasInteracted(true);
    }
    // 执行原始点击处理
    if (onClick) onClick();
  };

  return (
    <button
      className={`${theme} ${size}`}
      onClick={handleClick}
      onMouseEnter={handleMouseEnter}
      style={style}
    >
      <Flex justify="space-evenly" align="center">
        {icon}
        {text
          .toUpperCase()
          .split('')
          .map((char, index) => (
            <span key={index}>{char}</span>
          ))}
      </Flex>
    </button>
  );
};

export default Button;

// app/components/ui/common/Button.vue
<script setup lang="ts">
import { useSoundEffect } from "@/composables/useSoundEffect";
import { useSoundStore } from "@/stores/soundStore";
import type { ButtonParams } from "@/types/components";

const { effectsVolume } = useSoundStore();
const { text, size, icon, onClick, classList, style } = defineProps<ButtonParams>();

const undertaleSound = useSoundEffect("sounds/effects/undertale-button.wav");

const handleClick = () => {
	if (onClick) {
		onClick();
		if (effectsVolume) undertaleSound.play();
	}
};
</script>

<template>
	<button
		:class="`${size} ${classList ? classList : ''}`"
		@click="handleClick"
		:style="style"
		draggable="false"
	>
		<div class="container">
			<span class="icon">{{ icon }}</span>
			<span v-for="(char, index) in text.toUpperCase().split('')" :key="index">{{ char }}</span>
		</div>
	</button>
</template>

<style scoped lang="scss">
$base-height: 42px;
$base-width: 110px;
$base-size: 1;

/* ========== 默认（> 1199px）========== */
button {
	background: #000000;
	color: #ff7f27;
	text-align: right;
	font-weight: 900;
	font-family: "Mars Needs Cunnilingus";
	border-color: #ff7f27;
	border-style: solid;
	cursor: pointer;
	user-select: none;

	&.small {
		height: $base-height * $base-size;
		width: $base-width * $base-size;
		font-size: 1.3rem * $base-size;
		border-width: 0.25rem * $base-size;
	}

	&.medium {
		height: $base-height * $base-size * 1.5;
		width: $base-width * $base-size * 1.5;
		font-size: 2rem * $base-size;
		border-width: 0.35rem * $base-size;
	}

	&.large {
		height: $base-height * $base-size * 2;
		width: $base-width * $base-size * 2;
		font-size: 2.5rem * $base-size;
		border-width: 0.5rem * $base-size;
	}

	&:hover {
		color: #ffff00;
		border-color: #ffff00;
	}

	.container {
		display: flex;
		justify-content: space-evenly;
		align-items: center;
	}
}

/* ========== 超小屏（< 576px）========== */
@media screen and (max-width: 576px) {
	$base-size: 0.3;

	button {
		&.small {
			height: $base-height * $base-size * 2;
			width: $base-width * $base-size * 2;
			font-size: 2.3rem * $base-size;
			border-width: 0.6rem * $base-size;
		}

		&.large {
			height: $base-height * $base-size * 2;
			width: $base-width * $base-size * 2;
			font-size: 2.5rem * $base-size;
			border-width: 0.6rem * $base-size;
		}
	}
}

/* ========== 小屏（576px - 768px）========== */
@media screen and (min-width: 576px) and (max-width: 768px) {
	$base-size: 0.45;

	button {
		&.small {
			height: $base-height * $base-size * 1.7;
			width: $base-width * $base-size * 1.7;
			font-size: 2rem * $base-size;
			border-width: 0.5rem * $base-size;
		}

		&.large {
			height: $base-height * $base-size * 2;
			width: $base-width * $base-size * 2;
			font-size: 2.5rem * $base-size;
			border-width: 0.6rem * $base-size;
		}
	}
}

/* ========== 中等屏（768px - 991px）========== */
@media screen and (min-width: 768px) and (max-width: 991px) {
	$base-size: 0.6;

	button {
		&.small {
			height: $base-height * $base-size * 1.5;
			width: $base-width * $base-size * 1.5;
			font-size: 1.8rem * $base-size;
			border-width: 0.4rem * $base-size;
		}

		&.large {
			height: $base-height * $base-size * 2;
			width: $base-width * $base-size * 2;
			font-size: 2.5rem * $base-size;
			border-width: 0.5rem * $base-size;
		}
	}
}

/* ========== 大屏（991px - 1199px）========== */
@media screen and (min-width: 991px) and (max-width: 1199px) {
	$base-size: 0.8;

	button {
		&.small {
			height: $base-height * $base-size * 1.3;
			width: $base-width * $base-size * 1.3;
			font-size: 1.6rem * $base-size;
			border-width: 0.35rem * $base-size;
		}

		&.large {
			height: $base-height * $base-size * 2;
			width: $base-width * $base-size * 2;
			font-size: 2.5rem * $base-size;
			border-width: 0.5rem * $base-size;
		}
	}
}
</style>
